name: Scrape
on: push
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - run: gem install google_drive
      - name: Run
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS}}
        run: ruby main.rb
